### PR TITLE
`Paywalls`: added `sub_duration_in_months` variable

### PR DESCRIPTION
**Pull request by NachoSoto**
- https://github.com/RevenueCat/purchases-ios/pull/3131
- https://github.com/RevenueCat/purchases-ios/pull/3173

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]

**Comment by NachoSoto** [comment]
Holding until they're available in the dashboard.

**Review by aboedo — APPROVED** [review]

**Comment by aboedo** [comment]
@NachoSoto they're available, right?

**Comment by NachoSoto** [comment]
The Linears for them are still open. I'll check in a bit.

**Comment by NachoSoto** [comment]
@aboedo yeah neither of them are available in the dashboard yet (cc @dpannasch)

**Pull request merged**
