### PR TITLE
Syncing 3f311f4 with v5.1

### PR DESCRIPTION
**Pull request by RCGitBot**
⚠️⚠️⚠️ APPROVE THE HOLD JOB IN THIS PR TO SYNC THE DOCS WITH WITH README ⚠️⚠️⚠️
⚠️⚠️⚠️ MERGE THE PULL REQUEST WHEN SYNCING HAS FINISHED AND ALL CHECKS HAVE PASSED ⚠️⚠️⚠️
Syncing docs to release v5.1 of the docs. This PR was automatically generated by the RevenueCat bot.

### CODE REVIEW

**Review by WesleyClarkRC — COMMENTED** [review]
Looks fantastic

**Comment by NachoSoto** [comment]
@WesleyClarkRC good to deploy this?

**Comment by WesleyClarkRC** [comment]
@NachoSoto yep, good to deploy, I am just having permissions issues with circleCI that I am trying to resolve with Cody

**Comment by NachoSoto** [comment]
No worries, just wanted to know before I deployed something else. I'll approve this for you :)

**Comment by WesleyClarkRC** [comment]
thanks, I very much appreciate it

**Review by NachoSoto — APPROVED** [review]

**Pull request merged**
